chat:
  public:
    format: '&7[&6Global&7] %DISPLAYNAME%&7: &r%MSG%'
  private:
    format: '&7[%DISPLAYNAME% &7>> %TARGETDISPLAYNAME%&7] &r%MSG%'
  local:
    format: '&7[&2Local&7] %DISPLAYNAME%&7: &r%MSG%'
    radius: 150
  emote:
    format: ' * %DISPLAYNAME%&r %MSG%'
  admin:
    format: '&7[&4Admin&7] &c%NAME%&7: &r%MSG%'
    players: ''
  socialspy:
    format: '&6 + &7[%DISPLAYNAME% &7-> %TARGETDISPLAYNAME%&7] &r%MSG%'
    players: ''
    color: false
op:
  prefix: ''
  suffix: ''
userlist:
  display-prefix: true
  display-suffix: false
head:
  tag: true
log:
  public: true
  private: true
  admin: true
  local: true
  emote: true
  commands: true
console:
  color: true
  debug:
    public: true
    private: true
    admin: true
    local: true
    emote: true
    commands: false
locale: 'en'
version: '2.0.0'