#############################################
#                                           #
#          LiveChat config's file           #
#                                           #
#############################################
# You can use all color codes:              #
# BLACK         &0    | AQUA           &b   #
# DARK BLUE     &1    | RED            &c   #
# DARK GREEN    &2    | LIGHT PURPLE   &d   #
# DARK AQUA     &3    | YELLOW         &e   #
# DARK RED      &4    | WHITE          &f   #
# DARK PURPLE   &5    | MAGIC          &k   #
# GOLD          &6    | BOLD           &l   #
# GRAY          &7    | STRIKETHROUGH  &m   #
# DARK GRAY     &8    | UNDERLINE      &n   #
# BLUE          &9    | ITALIC         &o   #
# GREEN         &a    | RESET          &r   #
#############################################
# Parameters allowed on chat format:        #
# %DISPLAYNAME%       | %GAMEMODE%          #
# %NAME%              | %HEALTH%            #
# %MSG%               | %FOOD%              #
# %GROUPNAME%         | %LEVEL%             #
# %PREFIX%            | %TOTALXP%           #
# %SUFFIX%            | %TIME%              #
# %WORLDNAME%         |                     #
#############################################

# If you don't want to use the LiveChat's format change
# this option to 'DISABLED'.
chat-format: '&7[&6%GROUPNAME%&7]&r %DISPLAYNAME%&7:&r %MSG%'

# Custom format for </me>.
emote-format: ' * %DISPLAYNAME% %MSG%'

# Local message values.
local-format: '&8{&7%DISPLAYNAME%&8} &6=>&r %MSG%'
local-radius: 150

# Remember that Minecraft doesn't support more than 16 characters
# nicknames, this includes color codes. If the nickname exceeds
# the limit this option doesn't work :-(
op-prefix: ''

# Players inside will receive all private messages.
# Comma-separated names.
socialspy-players: ''

# Players inside will be able to talk on the channel.
# Comma-separated names.
channel-admin-players: ''
channel-admin-format: '&c<@> %NAME%&7:&r %MSG%'

# Log files on your root Bukkit directory.
# 'server.public.log', 'server.private.log' and
# 'server.commands.log'.
log-public-chat: true
log-private-chat: true
log-commands: true

# DON'T CHANGE THIS VALUE!
version: '1.0.0'