name: LiveChat
main: com.gmail.zant95.LiveChat.LiveChat
version: 2.0.8
author: zant95
softdepend: [Vault]
description: A complete chat suite for CraftBukkit.
commands:
   tell:
      description: Sends a private message to the specified player.
      aliases: [lctell,whisper,msg,pm,t]
   reply:
      description: Quickly reply the last player messaged you.
      aliases: [lcreply,r]
   emote:
      description: Describes an action on the player's context.
      aliases: [lcme,action,me]
   map:
      description: Send a message in the actual map.
      aliases: [lcmap]
   local:
      description: Send a message in a specific radius.
      aliases: [lclocal]
   global:
      description: Send a public message.
      aliases: [lcglobal]
   mute:
      description: Mutes or unmutes a player.
      aliases: [lcmute]
   block:
      description: Block or unblock a player.
      aliases: [lcblock]
   ignore:
      description: Ignore or unignore a player/channel.
      aliases: [lcignore]
   socialspy:
      description: Enables/disables socialspy.
      aliases: [lcsocialspy]
   admin:
      description: Send a message on admin channel.
      aliases: [lcadmin]
   livechat:
      description: Main command of plugin LiveChat.
permissions:
   livechat.global.send:
      default: true
   livechat.global.receive:
      default: true
   livechat.global.color:
      default: true
   livechat.global.format:
      default: false
   livechat.global.magic:
      default: false
   livechat.private.send:
      default: true
   livechat.private.receive:
      default: true
   livechat.private.color:
      default: true
   livechat.private.format:
      default: false
   livechat.private.magic:
      default: false
   livechat.emote.send:
      default: true
   livechat.emote.receive:
      default: true
   livechat.emote.color:
      default: true
   livechat.emote.format:
      default: false
   livechat.emote.magic:
      default: false
   livechat.map.send:
      default: true
   livechat.map.receive:
      default: true
   livechat.map.color:
      default: true
   livechat.map.format:
      default: false
   livechat.map.magic:
      default: false
   livechat.local.send:
      default: true
   livechat.local.receive:
      default: true
   livechat.local.color:
      default: true
   livechat.local.format:
      default: false
   livechat.local.magic:
      default: false
   livechat.ignore:
      default: true
   livechat.ignore.bypass:
      default: false
   livechat.mute:
      default: false
   livechat.block:
      default: false
   livechat.colortag:
      default: true
   livechat.hear.bypass:
      default: false
   livechat.socialspy:
      default: false
   livechat.send:
      default: true
      children:
         livechat.global.send: true
         livechat.private.send: true
         livechat.emote.send: true
         livechat.map.send: true
         livechat.local.send: true
   livechat.receive:
      default: true
      children:
         livechat.global.receive: true
         livechat.private.receive: true
         livechat.emote.receive: true
         livechat.map.receive: true
         livechat.local.receive: true
   livechat.global:
      default: false
      children:
         livechat.global.send: true
         livechat.global.receive: true
         livechat.global.color: true
         livechat.global.format: true
         livechat.global.magic: true
   livechat.private:
      default: false
      children:
         livechat.private.send: true
         livechat.private.receive: true
         livechat.private.color: true
         livechat.private.format: true
         livechat.private.magic: true
   livechat.emote:
      default: false
      children:
         livechat.emote.send: true
         livechat.emote.receive: true
         livechat.emote.color: true
         livechat.emote.format: true
         livechat.emote.magic: true
   livechat.map:
      default: false
      children:
         livechat.map.send: true
         livechat.map.receive: true
         livechat.map.color: true
         livechat.map.format: true
         livechat.map.magic: true
   livechat.local:
      default: false
      children:
         livechat.local.send: true
         livechat.local.receive: true
         livechat.local.color: true
         livechat.local.format: true
         livechat.local.magic: true
   livechat.admin:
      default: op
      children:
         livechat.global: true
         livechat.private: true
         livechat.emote: true
         livechat.map: true
         livechat.local: true
         livechat.ignore: true
         livechat.mute: true
         livechat.block: true
         livechat.colortag: true
         livechat.socialspy: true